### ISSUE TITLE
Getting an Unexpected error while processing request: Body yielded non-string value

### ISSUE THREAD

**Issue by mosic** [Mashape/analytics-agent-ruby#2]
After updating to 1.0.2 I was getting this when I hit any endpoint (in this example it's `http://localhost:9292/v1/swagger.json`):

```
Listening on localhost:9292, CTRL+C to stop
NoMethodError: undefined method `inject' for #<Rack::Deflater::GzipStream:0x00000005f9c518>
    /home/jack/.rvm/gems/ruby-2.2.0/gems/mashape-analytics-1.0.2/lib/mashape-analytics/frameworks/rack.rb:132:in `response_content_size'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/mashape-analytics-1.0.2/lib/mashape-analytics/frameworks/rack.rb:144:in `record_alf'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/mashape-analytics-1.0.2/lib/mashape-analytics/frameworks/rack.rb:41:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/airbrake-4.2.1/lib/airbrake/rack.rb:46:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/bundler/gems/rack-ssl-enforcer-4e5bdac7af35/lib/rack/ssl-enforcer.rb:57:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/handler/thin.rb:19:in `run'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
    /home/jack/.rvm/gems/ruby-2.2.0/bin/rackup:23:in `load'
    /home/jack/.rvm/gems/ruby-2.2.0/bin/rackup:23:in `<main>'
    /home/jack/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    /home/jack/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
127.0.0.1 - - [25/Jun/2015:21:52:14 +0200] "GET /v1/swagger.json HTTP/1.1" 500 135576 0.1917
```

If I disable `Rack::Deflater` I get this error:

```
127.0.0.1 - - [25/Jun/2015:21:53:49 +0200] "GET /v1/swagger.json HTTP/1.1" 200 464 0.1563
Unexpected error while processing request: Body yielded non-string value ["{\n  \"apiVersion\": \"1.0\",\n  \"swaggerVersion\": \"1.2\",\n  \"produces\": [\n    \"application/json\"\n  ],\n  \"operations\": [\n\n  ],\n  \"apis\": [\n    {\n      \"path\": \"/swagger/users\"\n    },\n    {\n      \"path\": \"/swagger/cameras\"\n    },\n    {\n      \"path\": \"/swagger/public\"\n    },\n    {\n      \"path\": \"/swagger/models\"\n    },\n    {\n      \"path\": \"/swagger/vendors\"\n    },\n    {\n      \"path\": \"/swagger/auth\"\n    }\n  ],\n  \"info\": {\n  },\n  \"basePath\": \"http://localhost:9292/v1\"\n}"]
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:20:in `assert'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:710:in `block in each'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:708:in `each'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/response.rb:96:in `each'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:114:in `post_process'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/handler/thin.rb:19:in `run'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
    /home/jack/.rvm/gems/ruby-2.2.0/bin/rackup:23:in `load'
    /home/jack/.rvm/gems/ruby-2.2.0/bin/rackup:23:in `<main>'
    /home/jack/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    /home/jack/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

You can see what the response normally looks like here: https://api.evercam.io/v1/swagger.json

**Comment by kennethklee** [comment]
@mosic hey maybe you could help me run evercam locally and i can wring out all the issues with the agent. How do i get started on it?

I have a postgres db. 

For the evercam-dashboard, I've edited the database.yml file for it. And `rake db:migrate` is giving me nothing but a new table called `schema_migrations`. How do I create the tables?

**Comment by mosic** [comment]
@kennethklee Easiest way would be to use our dev setup, it sets up both `evercam-api` and `evercam-dashboard`: https://github.com/evercam/evercam-devops

Let me know if anything doesn't work for you.

**Comment by kennethklee** [comment]
@mosic hey what's the password to the vagrant box?

``` shell
kenneth@kenneth-mashape:~/projects/evercam-devops$ vagrant ssh
==> default: The machine you're attempting to SSH into is configured to use
==> default: password-based authentication. Vagrant can't script entering the
==> default: password for you. If you're prompted for a password, please enter
==> default: the same password you have configured in the Vagrantfile.
vagrant@127.0.0.1's password: 
```

**Comment by kennethklee** [comment]
So instead I released a new version with a fix for the errors above, as well as a few more checks here and there. See v1.0.3.

Lemme know if there are any more issues.

**Comment by mosic** [comment]
@kennethklee The password is "vagrant", it's mentioned on that page. If I disable `Rack::Deflater` everything seems to work now, the data is sent and visible on Mashape Analytics dashboard, so that's great.

Any idea why it is erroring with `Rack::Deflater`? Here is a sample error output:

```
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on localhost:9292, CTRL+C to stop
NoMethodError: undefined method `call' for nil:NilClass
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/deflater.rb:94:in `write'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/mashape-analytics-1.0.3/lib/mashape-analytics/frameworks/rack.rb:105:in `stream_size'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/mashape-analytics-1.0.3/lib/mashape-analytics/frameworks/rack.rb:151:in `response_content_size'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/mashape-analytics-1.0.3/lib/mashape-analytics/frameworks/rack.rb:166:in `record_alf'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/mashape-analytics-1.0.3/lib/mashape-analytics/frameworks/rack.rb:41:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/airbrake-4.2.1/lib/airbrake/rack.rb:46:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/bundler/gems/rack-ssl-enforcer-4e5bdac7af35/lib/rack/ssl-enforcer.rb:57:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/handler/thin.rb:19:in `run'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
    /home/jack/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
    /home/jack/.rvm/gems/ruby-2.2.0/bin/rackup:23:in `load'
    /home/jack/.rvm/gems/ruby-2.2.0/bin/rackup:23:in `<main>'
    /home/jack/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    /home/jack/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
127.0.0.1 - - [30/Jun/2015:02:02:02 +0200] "GET /v1/swagger.json HTTP/1.1" 500 140309 0.1753
```

**Comment by kennethklee** [comment]
There's a whole slew of failed tests for the api. And dashboard tests can't seem to run at all.

``` shell
Failed examples:

rspec ./spec/actors/share_create_for_request_spec.rb:28 # Evercam::Actors::ShareCreateForRequest when given valid parameters creates a share with the requesting user as the sharer
rspec ./spec/actors/share_create_spec.rb:54 # Evercam::Actors::ShareCreate when given valid parameters for a user that already exists in the system creates a private share for a private camera
rspec ./spec/actors/share_create_spec.rb:63 # Evercam::Actors::ShareCreate when given valid parameters for a user that already exists in the system creates a private share for a public camera
rspec ./spec/actors/share_create_spec.rb:31 # Evercam::Actors::ShareCreate when given valid parameters for a user that already exists in the system that do not include a grantor creates a share with the camera owner as the sharer
rspec ./spec/actors/share_create_spec.rb:42 # Evercam::Actors::ShareCreate when given valid parameters for a user that already exists in the system that do include a grantor create a share with the grantor as the sharer
rspec ./spec/actors/share_create_spec.rb:82 # Evercam::Actors::ShareCreate when given valid parameters for a user that does not exists in the system that do not include a grantor creates a share with the camera owner as the sharer
rspec ./spec/actors/share_create_spec.rb:93 # Evercam::Actors::ShareCreate when given valid parameters for a user that does not exists in the system that do include a grantor create a share with the grantor as the sharer
rspec ./spec/app/api/v1/routes/public_routes_spec.rb:106 # API routes/cameras GET /public/cameras when is_near_to is specified as an address string returns success and the correct camera entries
rspec ./spec/app/api/v1/routes/share_routes_spec.rb:121 # API routes/cameras POST /cameras/:id/shares/ where the user email does not exist returns success
rspec ./spec/app/api/v1/routes/share_routes_spec.rb:131 # API routes/cameras POST /cameras/:id/shares/ when a proper request is sent by the camera owner returns success
rspec ./spec/app/api/v1/routes/share_routes_spec.rb:151 # API routes/cameras POST /cameras/:id/shares/ when a proper request is sent by a user with edit rights on the camera returns success
```

But regardless, both run. Gonna try adding the middleware and seeing if I can reproduce.

**Comment by kennethklee** [comment]
@mosic So I've added to both, and I'm not seeing the errors with either, even with gzip enabled.

Perhaps I'm doing something wrong.

In evercam-api, I added analytics to `config.ru` here:

``` ruby
  # Enable gzip
  use Rack::Deflater

  # Enable Analytics
  use MashapeAnalytics::Frameworks::Rack, ...

  run Evercam::APIv1
```

Also running the server with
`bundle exec rackup`

Hitting the server with curl, I get this in the logs:

``` shell
vagrant@vagrant-ubuntu-trusty-64:/vagrant/evercam-api$ bundle exec rackup
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sinatra-contrib-1.4.4/lib/sinatra/respond_with.rb:4: warning: variable $KCODE is no longer effective; ignored
COMMAND  PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ruby    5263 vagrant    7u  IPv4  16969      0t0  TCP *:10453 (LISTEN)
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on localhost:9292, CTRL+C to stop
127.0.0.1 - - [30/Jun/2015:19:47:56 +0000] "GET /v1/swagger.json HTTP/1.1" 200 464 0.2443
```

**Comment by mosic** [comment]
@kennethklee That's strange, tests are passing for me on that branch ([and on the master branch on TravisCI](https://travis-ci.org/evercam/evercam-api)).

Funny, it does work using curl, but not when hitting the same url in the browser (I get the error above). You can replicate this error with curl if you specify "Accept-Encoding" header:

```
curl -H "Accept-Encoding: gzip" http://localhost:9292/v1/swagger.json
```

**Comment by kennethklee** [comment]
@mosic seems to be okay; no errors. Not sure what I'm doing wrong.

I'm curling with `Accept-Encoding: gzip`. Getting back an encrypted response. Server logs the call. And i see it in Mashape Analytics with the header.

**Comment by mosic** [comment]
Hm, that's weird. I'll see if I can demonstrate this, will get back to you some other time. You can close this for now if that's okay.

Btw you're getting an encrypted response? We're not using https in development so I don't see why that would be the case.

**Comment by kennethklee** [comment]
sorry, it was a garbled response. could have been gzip compressed.

closing for now.
